niches:
  veltrix:
    description: "AI, Quant Finance, Coding"
    keywords_filter:
      - "ai"
      - "finance"
      - "fintech"
      - "trading"
      - "stocks"
      - "chatgpt"
      - "wealth"
      - "claude"
      - "gemini"
      - "tech"
      - "playwright"
      - "automation"
      - "openai"
      - "python"
      - "coding"
      - "crypto"
      - "nvidia"
      - "investing"
